name: Make Release

on:
  push:
    tags:
      - 'v**'

jobs:
  make_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare Environment
        run: |
          rustup update stable
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: OscAvMgr ${{ github.ref_name }}
          draft: true
          prerelease: false

      - name: Cargo Build ALVR
        run: |
          cargo build --no-default-features --features=alvr --release
          chmod +x target/release/oscavmgr

      - name: Upload ALVR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/oscavmgr
          asset_name: oscavmgr-alvr
          asset_content_type: application/octet-stream

      - name: Cargo Build WiVRn
        run: |
          cargo build --no-default-features --features=wivrn --release
          chmod +x target/release/oscavmgr

      - name: Upload WiVRn
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/oscavmgr
          asset_name: oscavmgr-wivrn
          asset_content_type: application/octet-stream

      - name: Cargo Build Babble
        run: |
          cargo build --no-default-features --features=babble --release
          chmod +x target/release/oscavmgr

      - name: Upload Babble
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/oscavmgr
          asset_name: oscavmgr-babble
          asset_content_type: application/octet-stream

